rp: add stubs to enable incremental typing
Problem: mypy was reporting:
```
src/psi/j/executors/rp.py:142: error: Returning Any from function declared to return "Dict[str, Any]"
```
since the missing import defaults to `Any` but the explitict return type
was more specific.

Solution: add a stub for radical and add return type for the
`TaskDescription` function